IF (PSRDADA_CPP_INCLUDE_DIR)
    SET(PSRDADA_CPP_INC_DIR ${PSRDADA_CPP_INCLUDE_DIR})
    UNSET(PSRDADA_CPP_INCLUDE_DIR)
ENDIF (PSRDADA_CPP_INCLUDE_DIR)

FIND_PATH(PSRDADA_CPP_INCLUDE_DIR dada_def.h
    PATHS ${PSRDADA_CPP_INC_DIR}
    ${PSRDADA_CPP_INSTALL_DIR}/include
    /usr/local/include
    /usr/include )
message("Found ${PSRDADA_CPP_INCLUDE_DIR} : ${PSRDADA_CPP_INSTALL_DIR}")

SET(PSRDADA_CPP_NAMES psrdada_cpp)
FOREACH( lib ${PSRDADA_CPP_NAMES} )
    FIND_LIBRARY(PSRDADA_CPP_LIBRARY_${lib}
        NAMES ${lib}
        PATHS ${PSRDADA_CPP_LIBRARY_DIR} ${PSRDADA_CPP_INSTALL_DIR} ${PSRDADA_CPP_INSTALL_DIR}/lib /usr/local/lib /usr/lib
        )
    LIST(APPEND PSRDADA_CPP_LIBRARIES ${PSRDADA_CPP_LIBRARY_${lib}})
ENDFOREACH(lib)

    # handle the QUIETLY and REQUIRED arguments and set PSRDADA_CPP_FOUND to TRUE if.
    # all listed variables are TRUE
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(PSRDADA_CPP DEFAULT_MSG PSRDADA_CPP_LIBRARIES PSRDADA_CPP_INCLUDE_DIR)

IF(NOT PSRDADA_CPP_FOUND)
    SET( PSRDADA_CPP_LIBRARIES )
    SET( PSRDADA_CPP_TEST_LIBRARIES )
ELSE(NOT PSRDADA_CPP_FOUND)
    # -- add dependecies
    LIST(APPEND PSRDADA_CPP_LIBRARIES ${CUDA_curand_LIBRARY})
ENDIF(NOT PSRDADA_CPP_FOUND)

LIST(APPEND PSRDADA_CPP_INCLUDE_DIR "${PSRDADA_CPP_INCLUDE_DIR}")

MARK_AS_ADVANCED(PSRDADA_CPP_LIBRARIES PSRDADA_CPP_TEST_LIBRARIES PSRDADA_CPP_INCLUDE_DIR)
