IF (SPEAD2_INCLUDE_DIR)
    SET(SPEAD2_INC_DIR ${SPEAD2_INCLUDE_DIR})
    UNSET(SPEAD2_INCLUDE_DIR)
ENDIF (SPEAD2_INCLUDE_DIR)

FIND_PATH(SPEAD2_INCLUDE_DIR spead2/recv_heap.h
    PATHS ${SPEAD2_INC_DIR}
    ${SPEAD2_INSTALL_DIR}/include
    /usr/local/include
    /usr/include )
message("Found ${SPEAD2_INCLUDE_DIR} : ${SPEAD2_INSTALL_DIR}")

SET(SPEAD2_NAMES spead2)
FOREACH( lib ${SPEAD2_NAMES} )
    FIND_LIBRARY(SPEAD2_LIBRARY_${lib}
        NAMES ${lib}
        PATHS ${SPEAD2_LIBRARY_DIR} ${SPEAD2_INSTALL_DIR} ${SPEAD2_INSTALL_DIR}/lib /usr/local/lib /usr/lib
        )
    LIST(APPEND SPEAD2_LIBRARIES ${SPEAD2_LIBRARY_${lib}})
ENDFOREACH(lib)

    # handle the QUIETLY and REQUIRED arguments and set SPEAD2_FOUND to TRUE if.
    # all listed variables are TRUE
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SPEAD2 DEFAULT_MSG SPEAD2_LIBRARIES SPEAD2_INCLUDE_DIR)

IF(NOT SPEAD2_FOUND)
    SET( SPEAD2_LIBRARIES )
    SET( SPEAD2_TEST_LIBRARIES )
ELSE(NOT SPEAD2_FOUND)
    # -- add dependecies
    LIST(APPEND SPEAD2_LIBRARIES ${CUDA_curand_LIBRARY})
ENDIF(NOT SPEAD2_FOUND)

LIST(APPEND SPEAD2_INCLUDE_DIR "${SPEAD2_INCLUDE_DIR}")

MARK_AS_ADVANCED(SPEAD2_LIBRARIES SPEAD2_TEST_LIBRARIES SPEAD2_INCLUDE_DIR)
